// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Space struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	IsPrivate  bool
	CreatedAt  time.Time
	ModifiedAt time.Time
}

type User struct {
	ID            uuid.UUID
	Email         string
	Password      string
	Username      string
	UsernameLower sql.NullString
	DisplayName   string
	Provider      string
	ProviderID    sql.NullString
	CreatedAt     time.Time
	ModifiedAt    time.Time
}

type Widget struct {
	ID         uuid.UUID
	SpaceID    uuid.UUID
	Type       string
	XPos       int32
	YPos       int32
	Minimized  bool
	Data       json.RawMessage
	CreatedAt  time.Time
	ModifiedAt time.Time
}
