// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID            uuid.UUID
	Name          sql.NullString
	Email         string
	Password      sql.NullString
	EmailVerified time.Time
}

type VerificationCode struct {
	ID        uuid.UUID
	Email     string
	Code      string
	Used      bool
	ExpiresAt time.Time
}
