// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sessions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id, user_id, revoked, expires_at, created_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id
`

type CreateSessionParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Revoked   bool
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Revoked,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSessionExpiration = `-- name: GetSessionExpiration :one
SELECT expires_at FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionExpiration(ctx context.Context, id uuid.UUID) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getSessionExpiration, id)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}
