// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, name, email, password, salt, email_verified
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id
`

type CreateUserParams struct {
	ID            uuid.UUID
	Name          sql.NullString
	Email         string
	Password      sql.NullString
	Salt          sql.NullString
	EmailVerified time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Salt,
		arg.EmailVerified,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUser = `-- name: GetUser :one
SELECT
    id,
    name,
    email,
    password,
    salt,
    email_verified
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID            uuid.UUID
	Name          sql.NullString
	Email         string
	Password      sql.NullString
	Salt          sql.NullString
	EmailVerified time.Time
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Salt,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    name,
    email,
    password,
    salt,
    email_verified
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID            uuid.UUID
	Name          sql.NullString
	Email         string
	Password      sql.NullString
	Salt          sql.NullString
	EmailVerified time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Salt,
		&i.EmailVerified,
	)
	return i, err
}
