// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: verification_codes.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVerificationCode = `-- name: CreateVerificationCode :exec
INSERT INTO verification_codes (
    id, email, code, used, expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateVerificationCodeParams struct {
	ID        uuid.UUID
	Email     string
	Code      string
	Used      bool
	ExpiresAt time.Time
}

func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) error {
	_, err := q.db.ExecContext(ctx, createVerificationCode,
		arg.ID,
		arg.Email,
		arg.Code,
		arg.Used,
		arg.ExpiresAt,
	)
	return err
}

const getValidVerificationCode = `-- name: GetValidVerificationCode :one
SELECT id
FROM verification_codes
WHERE
    email = $1
    AND code = $2
    AND used = FALSE
    AND expires_at > NOW()
LIMIT 1
`

type GetValidVerificationCodeParams struct {
	Email string
	Code  string
}

func (q *Queries) GetValidVerificationCode(ctx context.Context, arg GetValidVerificationCodeParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getValidVerificationCode, arg.Email, arg.Code)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setUsedVerificationCode = `-- name: SetUsedVerificationCode :exec
UPDATE verification_codes
SET used = TRUE
WHERE
    id = $1
`

func (q *Queries) SetUsedVerificationCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setUsedVerificationCode, id)
	return err
}
