// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: verification_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVerificationToken = `-- name: CreateVerificationToken :exec
INSERT INTO verification_tokens (
    id, email, token, used, expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateVerificationTokenParams struct {
	ID        uuid.UUID
	Email     string
	Token     string
	Used      bool
	ExpiresAt time.Time
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) error {
	_, err := q.db.ExecContext(ctx, createVerificationToken,
		arg.ID,
		arg.Email,
		arg.Token,
		arg.Used,
		arg.ExpiresAt,
	)
	return err
}
