// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: widgets.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createWidget = `-- name: CreateWidget :one
INSERT INTO widgets (
    id, space_id, type, x_pos, y_pos, minimized, data
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, space_id, type, x_pos, y_pos, minimized, data, created_at, modified_at
`

type CreateWidgetParams struct {
	ID        uuid.UUID
	SpaceID   uuid.UUID
	Type      string
	XPos      int32
	YPos      int32
	Minimized bool
	Data      json.RawMessage
}

func (q *Queries) CreateWidget(ctx context.Context, arg CreateWidgetParams) (Widget, error) {
	row := q.db.QueryRowContext(ctx, createWidget,
		arg.ID,
		arg.SpaceID,
		arg.Type,
		arg.XPos,
		arg.YPos,
		arg.Minimized,
		arg.Data,
	)
	var i Widget
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Type,
		&i.XPos,
		&i.YPos,
		&i.Minimized,
		&i.Data,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getWidgetsBySpaceID = `-- name: GetWidgetsBySpaceID :many
SELECT id, space_id, type, x_pos, y_pos, minimized, data, created_at, modified_at FROM widgets
WHERE space_id = $1
`

func (q *Queries) GetWidgetsBySpaceID(ctx context.Context, spaceID uuid.UUID) ([]Widget, error) {
	rows, err := q.db.QueryContext(ctx, getWidgetsBySpaceID, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Widget
	for rows.Next() {
		var i Widget
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Type,
			&i.XPos,
			&i.YPos,
			&i.Minimized,
			&i.Data,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWidget = `-- name: UpdateWidget :one
UPDATE widgets
SET x_pos = $2, y_pos = $3, minimized = $4, data = $5
WHERE id = $1
RETURNING id, space_id, type, x_pos, y_pos, minimized, data, created_at, modified_at
`

type UpdateWidgetParams struct {
	ID        uuid.UUID
	XPos      int32
	YPos      int32
	Minimized bool
	Data      json.RawMessage
}

func (q *Queries) UpdateWidget(ctx context.Context, arg UpdateWidgetParams) (Widget, error) {
	row := q.db.QueryRowContext(ctx, updateWidget,
		arg.ID,
		arg.XPos,
		arg.YPos,
		arg.Minimized,
		arg.Data,
	)
	var i Widget
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Type,
		&i.XPos,
		&i.YPos,
		&i.Minimized,
		&i.Data,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
